version: "3"

services:
  development:
    image: node:12.8.1-alpine
    ports:
      - "22:2000"
      - "80:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=local
    working_dir: /app
    volumes:
      - ssh:/app/ssh
      - ./:/app
    command: ["npm", "run", "start"]

volumes:
  ssh: {}
