tunnel:
  build: .
  environment:
    - NODE_ENV=production
  ports:
    - "80:80"
    - "443:443"
    - "22:22"

dev:
  build: .
  environment:
    - NODE_ENV=development
  ports:
    - "80:80"
    - "443:443"
    - "22:22"
