version: '2.1'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      development:
        condition: service_healthy
      certbot:
        condition: service_healthy
    volumes:
      - ./server/nginx.development.conf:/etc/nginx/nginx.conf
    ports:
      - "22:22"
      - "443:443"
    volumes_from:
      - certbot
  development:
    image: app
    env_file:
      - ./.env
    environment:
      - NODE_ENV=local
  certbot:
    build:
      context: .
      dockerfile: Dockerfile.certbot
    env_file: .env
    environment:
      - APP_HOSTNAME=tunnelvision.me
    volumes:
      - ~/.aws:/root/.aws:ro

volumes:
  ssh: {}
  certbot: {}
