version: '3'

services:
  tunnel:
    build: 
      context: .
      args:
        NODE_ENV: production
    ports:
      - "8080:8080"
      - "80:80"
      - "22:22"
  dev:
    build: 
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8080:8080"
      - "80:80"
      - "22:22"
    volumes:
      - ./src:/var/app/src
    command: ["npx", "ts-node-dev", "--respawn", "--transpileOnly", "./src/index.ts"]
