version: '3'

services:
  tunnel:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
      - "80:8080"
      - "22:2222"
  dev:
    build:
      context: .
      args:
        NODE_ENV: development
        DOMAIN: localhost
    ports:
      - "3000:3000"
      - "80:8080"
      - "22:2222"
    volumes:
      - ./src:/var/app/src
    command: ["npx", "ts-node-dev", "--respawn", "--transpileOnly", "./src/index.ts"]
