version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - development
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - ./server/nginx.development.conf:/etc/nginx/nginx.conf
      - ./server/public_html:/var/www/html
  development:
    image: node:12.8.1-alpine
    env_file:
      - ./.env
    environment:
      - NODE_ENV=local
    working_dir: /app
    volumes:
      - ssh:/app/ssh
      - ./:/app
    command: ["npm", "run", "start"]
  certbot:
    image: certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    env_file: .env
    environment:
      - APP_HOSTNAME=tunnelvision.me
    volumes:
      - ~/.aws:/root/.aws:ro

volumes:
  ssh: {}
