version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - tunnelvision
      - certbot
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/tls.conf:/etc/nginx/tls.conf
      - ./server/ffdhe4096.pem:/etc/nginx/ffdhe4096.pem
      - ./server/public_html:/var/www/html

  tunnelvision:
    image: node:12.8.1-alpine
    env_file:
      - ./.env
    volumes:
      - ssh:/ssh
      - ./server/dist:/app:ro
      - ./node_modules:/node_modules:ro
    command: ["node", "/app/src"]
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /aws/tunnelvision

  certbot:
    image: certbot/dns-route53
    env_file:
      - ./.env
    volumes:
      - ./server/letsencrypt.sh:/letsencrypt.sh:ro
      - letsencrypt:/etc/letsencrypt
    entrypoint: ["sh", "/letsencrypt.sh"]
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /aws/tunnelvision/certbot

volumes:
  letsencrypt: {}
  ssh: {}
